export const ActivityLogType = {
  Update: "Update",
  Create: "Create",
  Delete: "Delete",
  Delete_Account: "Delete Account",
  Data_entry_submission: "Data entry submission",
  Branch_entry_update: "Branch entry status Update",
  Branch_entry_create: "Church Branch created",
  Branch_entry_edit: "Church Branch edited",
  Church_entry_create: "Church Created",
  Church_entry_update: "Church Updated",
  Church_entry_delete: "Church Deleted",
  Approval_entry_update: "Approval status Update",
  Created_account: "Created account",
  Log_in: "Log in",
  Log_out: "Log out",
  Data_entry_edit: "Data entry edit",
  Changed_password: "Changed password",
  Register_user: "Register user",
  Profile_update: "Profile update",
  Permission_update: "User Permission Updated",
};
